apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: ju6cl3v9p-dotnet-basic
  janus-idp.io/tekton: ju6cl3v9p-dotnet-basic
  backstage.io/kubernetes-id: ju6cl3v9p-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: ju6cl3v9p-dotnet-basic
resources:
  - deployment.yaml
  - route.yaml
  - service.yaml
